add todo steering committee blog post
todogroup/todogroup.org pull request #270
Opened 2021-12-27 14:39 UTC by anajsana

This new blog post introduces the new and remaining TODO SC Members elected and appointed for 2022

2021-12-27 22:29 UTC, vmbrasseur approved these changes
LGTM

2021-12-31 09:19 UTC, justaugustus requested changes
@anajsana -- Left a few suggestions!

One more!
Is it worth delineating between:
- net-new members (Shilla, Thomas, and myself)
- returning members (VM was on a previous SC)
- members who are continuing terms/re-{elected,appointed} (Ashley, Dawn, Stephen Jacobs)

?

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +**New Member**
```suggestion

**New Member**
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +
```suggestion

**New Member**
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +**Remaining Member**
```suggestion

**Returning Member**
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +
```suggestion

**New Member**
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +
```suggestion

**New Member**
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +
```suggestion
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +***
```suggestion
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +Last but not least, the TODO Group would like to extend a big 'thanks' to the outgoing TODO Members: Chris Aniszczyk , Duane O'Brien, Stormy Peters and Kevin P. Fleming.  Thanks to their guidance and
```suggestion
Last but not least, the TODO Group would like to extend a big 'thanks' to the outgoing Steering Committee members: Chris Aniszczyk, Duane O'Brien, Stormy Peters, and Kevin P. Fleming. Thanks to their guidance and expertise in OSPOs, they have made outstanding contributions to the project's governance and the community.
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +If you wish to learn more about the Steering Commitee please check [TODO Governance repo](https://github.com/todogroup/governance).
```suggestion
If you want to learn more about the Steering Committee, please check out the [TODO Governance repo](https://github.com/todogroup/governance).
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +Ashley is a passionate advocate for open source. She is currently the Open Source Program Manager at GitHub. Prior to GitHub, she led the Yahoo (acquired by Verizon) open source program and worked in
```suggestion
Ashley is a passionate advocate for open source. She is currently the Open Source Program Manager at GitHub. Prior to GitHub, she led the Yahoo (acquired by Verizon) open source program and worked in product management for a cybersecurity company. Ashley serves on steering committees for open source foundations and is an advisor for Built by Girls, an organization that prepares the next generation of female and non-binary leaders to step boldly into careers powered by technology.
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +Across the wider CNCF (Cloud Native Computing Foundation) ecosystem, Stephen has the pleasure of serving as a SIG Contributor Strategy Chair, and a maintainer for the Dex project. Previously, he was
```suggestion
Across the wider CNCF (Cloud Native Computing Foundation) ecosystem, Stephen has the pleasure of serving as a TAG Contributor Strategy Chair, and a maintainer for the Dex project. Previously, he was one of the Program Chairs for KubeCon / CloudNativeCon, the cloud native community’s flagship conference. He is a prolific contributor to CNCF projects, amongst the top 25 (as of writing) code/content committers, all-time.
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +TODO Steering Committee is represented by global Open Source leaders and OSPO professionals, coming from a diverse range of industries.
```suggestion
TODO Steering Committee is composed of global Open Source leaders and OSPO professionals from a diverse range of industries.
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +Now that elections closed and results are published, we are proud to introduce the new Steering Committee members for 2022:
```suggestion
Now that the 2021 election has been completed, we are proud to introduce the new Steering Committee members for 2022:
```

2021-12-31 09:19 UTC, justaugustus commented on content/en/blog/todo-steering-committee-2022.md
> +* [Stephen Augustus](https://twitter.com/stephenaugustus) - Cisco
```suggestion
* [Stephen Augustus](https://whois.auggie.dev/) - Cisco
```

2021-12-31 09:23 UTC, justaugustus requested changes
Also...

https://github.com/todogroup/todogroup.org/pull/270/commits/16c242beefbf6b7098de028bf18052bdd8645e1f and https://github.com/todogroup/todogroup.org/pull/270/commits/9b35d9db2acde264e5403ea5056c8e0ff5308dbb were merged as part of https://github.com/todogroup/todogroup.org/pull/267, so they can be rebased out of this PR.

2022-01-03 12:34 UTC, anajsana reviewed
LGTM! Thanks!

2022-01-03 14:44 UTC, merged