Add contributing guidelines for website resources
todogroup/todogroup.org pull request #275
Opened 2022-01-13 12:39 UTC by anajsana

There is no clear process where the TODO Community can contribute to OSPO use cases and/or TODO guides. This commit works as a first iteration to document a clear process for both resources and ease community contribution.

2022-01-13 16:22 UTC, justaugustus requested changes
@anajsana -- Do either of the referenced guides need to be PDFs? Can they instead be content on the website?

If that's fine, I'd suggest bringing into the website.
As for the proposed README.md, maybe it would be good to add them here instead: https://github.com/todogroup/todogroup.org/blob/main/content/en/guides/casestudies/_index.md

and then link the README to that website content.

2022-01-13 19:01 UTC, anajsana commented
> @anajsana -- Do either of the referenced guides need to be PDFs? Can they instead be content on the website?
> 
> If that's fine, I'd suggest bringing into the website. As for the proposed README.md, maybe it would be good to add them here instead: https://github.com/todogroup/todogroup.org/blob/main/content/en/guides/casestudies/_index.md
> 
> and then link the README to that website content.

Thanks a lot for taking the time to review this! 👍

Having them as website content is a good idea, but I'm concerned about the length of the page if we add all content in the `_index.md` (the page has already too many sections IMHO: https://todogroup.org/guides/). 

Maybe we can add them as a new `.md` entry (e.g https://github.com/todogroup/todogroup.org/blob/main/content/en/guides/casestudies/todo-contribution-guidelines.md) and add a short text at _index.md (e.g Please check the OSPO Case Study Submission Guidelines (link) to get started). What do you think?

2022-01-17 19:19 UTC, anajsana commented
> @anajsana -- Do either of the referenced guides need to be PDFs? Can they instead be content on the website?
> 
> If that's fine, I'd suggest bringing into the website. As for the proposed README.md, maybe it would be good to add them here instead: https://github.com/todogroup/todogroup.org/blob/main/content/en/guides/casestudies/_index.md
> 
> and then link the README to that website content.

FYI: I've opened a PR adding the contribution guidelines https://github.com/todogroup/todogroup.org/pull/276

2022-01-26 09:36 UTC, anajsana commented
As mentioned in PR https://github.com/todogroup/todogroup.org/pull/276, I'm going to merge this since it's contributing documentation from existing TODO resources. If anyone from the SC wants to review and make changes, please open a new PR 🙂

2022-01-26 09:37 UTC, merged