Update ospo-survey-2023.md links of Chinese and Japanese
todogroup/todogroup.org pull request #379
Opened 2023-05-29 07:37 UTC by node

Ref issue #378

2023-05-29 11:07 UTC, anajsana commented
Thank you so much @node! LGTM to merge the PR with the links to the JP and Chinese survey versions 👍 However before going any further, I have checked the surveys and it looks like some of the texts have not been translated in both languages (for instance, see screenshot attached). Are the links to the survey a work in progress? I just want to know before promoting this 🙂

![Screenshot 2023-05-29 at 13-02-32 2023 Open Source Program Office (OSPO) Survey](https://github.com/todogroup/todogroup.org/assets/43671777/07ad302a-4470-43ce-af9a-13519089e53c)

2023-05-29 12:16 UTC, node commented
Actually I know nothing about the translationw work of the survey questions 😿    I just found the multile language switch menu on the topright when open the survey link .

2023-05-31 11:48 UTC, anajsana requested changes

2023-05-31 11:48 UTC, anajsana commented on content/en/blog/ospo-survey-2023.md
> +* [日本語](https://www.research.net/r/S95X7PD?lang=ja)
```suggestion
* [日本語](https://www.research.net/r/SYL6GXD?lang=ja)
```
The CollaboTrans JP open source community has contributed to a Japanese version of the survey. This is the fixed link 🙂

2023-06-02 13:15 UTC, anajsana approved these changes

2023-06-18 14:26 UTC, merged