Add some translation pages in Chinese
todogroup/todogroup.org pull request #408
Opened 2023-10-24 05:22 UTC by sunny0826

The docs updated in this PR are:
- [x]  training
- [x] get-started 
- [x] case-studies/_index.md 
- [x] guides/_index.md

2023-10-24 06:10 UTC, node commented on config/_default/languages.yaml
> +      name: "普通会员"
这里应是 伙伴？

2023-10-24 06:10 UTC, node commented on config/_default/languages.yaml
> +      name: "成员"
这里应是 普通会员 ？

2023-10-24 06:14 UTC, node commented on content/zh-CN/associates.md
> +*注意：OSPO 合作伙伴计划与 TODO Group 的普通会员资格不同，并且没有普通会员的权益。*
**TODO Group** 统一优化为 **TODO 小组**？与上下文保持一致

2023-10-24 06:18 UTC, node requested changes

2023-10-24 06:18 UTC, node commented on content/zh-CN/get-started.md
> +要随时了解关于OSPO的最新动态、职位、活动和研究，最直接的方法是[订阅 OSPO 每月新闻简报](https://ospo-news.ghost.io/)。
>OSPO 每月新闻简报 

此前我们统一称作 “OSPO 通讯月刊”

2023-10-24 06:32 UTC, sunny0826 commented on content/zh-CN/get-started.md
> +要随时了解关于OSPO的最新动态、职位、活动和研究，最直接的方法是[订阅 OSPO 每月新闻简报](https://ospo-news.ghost.io/)。
done

2023-10-25 07:14 UTC, node approved these changes

2023-10-25 07:15 UTC, node approved these changes
LGTM

2023-10-25 07:15 UTC, merged