Add Chinese translation for Using open source code
todogroup/todogroup.org pull request #412
Opened 2023-11-02 09:50 UTC by sunny0826

2023-11-02 10:22 UTC, node requested changes

2023-11-02 10:22 UTC, node commented on content/zh-CN/guides/using-open-source.md
> +一个开源项目的办公部门最主要的职责之一，是确保当你的组织把开源代码与商业产品的私有代码或第三方代码结合时，能满足法律规定。
开源项目办公室的重要职责之一，是.....

2023-11-02 10:22 UTC, node commented on content/zh-CN/guides/using-open-source.md
> +5. [在v1.0之后该怎么做](#在v10之后该怎么做)
v10 -> v1.0

2023-11-02 10:22 UTC, node commented on content/zh-CN/guides/using-open-source.md
> +开源项目办公部门可以帮助统一关于开源的消费、分发与发布的政策和决策，追踪代码的来源及使用，并保证公司不违背合规责任。
开源项目办公室

2023-11-02 10:22 UTC, node commented on content/zh-CN/guides/using-open-source.md
> +下面描述的是一个简化的合规审核流程视图。实际上，这一流程会更加迭代。值得注意的是，这些步骤只是为了说明，根据公司的具体需求和开源项目的配置，可能需要进行适当调整。
> 实际上，这一流程会更加迭代。

实际上，这是一个持续迭代的过程。

2023-11-02 10:22 UTC, node commented on content/zh-CN/guides/using-open-source.md
> +此阶段的目的是形成一个合法的建议，并对涉及的软件组件的许可证做出决策。这里提到的许可证可能有多种，因为在某些情况下，一个软件组件可能包含在多个许可证之下的源代码。在此阶段，存在三种可能的结论：
> 并对涉及的软件组件的许可证做出决策。

这里作为首次出现，建议对 incoming 和 outgoing 的翻译有一个统一，并且要考虑到下文的一致性。从含义上理解，全文指的是 license in & license out，中文里我们需要找到一个比较贴切的表达方式，有待进一步讨论，或者可以提到 译道师 微信群讨论下。

2023-11-02 10:22 UTC, node commented on content/zh-CN/guides/using-open-source.md
> +以下是对本项目的贡献者表示感谢：
'是' 字可以不要？

2023-11-02 10:31 UTC, sunny0826 commented on content/zh-CN/guides/using-open-source.md
> +5. [在v1.0之后该怎么做](#在v10之后该怎么做)
这里只有 `v10` 才能正确的跳转到指定位置

2023-11-02 12:14 UTC, node commented on content/zh-CN/guides/using-open-source.md
> +5. [在v1.0之后该怎么做](#在v10之后该怎么做)
那改为 v1 ? v10跨度有点儿大  😄

2023-11-02 13:06 UTC, sunny0826 commented on content/zh-CN/guides/using-open-source.md
> +5. [在v1.0之后该怎么做](#在v10之后该怎么做)
就是标题还是这个 `在v1.0之后该怎么做` 由于锚点的原因，只有这么写才能跳转到指定位置 https://deploy-preview-412--todogroup.netlify.app/zh-cn/resources/guides/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81/#%E5%9C%A8v10%E4%B9%8B%E5%90%8E%E8%AF%A5%E6%80%8E%E4%B9%88%E5%81%9A

2023-11-08 04:13 UTC, node approved these changes

2023-11-08 04:13 UTC, merged